# Generated by Django 2.1.3 on 2018-11-07 19:11

from django.db import migrations, models
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.AddField(
            model_name='game_1_obj',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
    ]
