# Generated by Django 2.1.4 on 2018-12-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20181205_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_2_Obj_Level_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Название')),
                ('image_1', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №1')),
                ('image_2', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №2')),
            ],
            options={
                'verbose_name': 'Объект игры №2 (уровень 1)',
                'verbose_name_plural': 'Массив изображений №2 (уровень 1)',
            },
        ),
        migrations.CreateModel(
            name='Game_2_Obj_Level_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Название')),
                ('image_1', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №1')),
                ('image_2', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №2')),
                ('image_3', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №3')),
            ],
            options={
                'verbose_name': 'Объект игры №2 (уровень 2)',
                'verbose_name_plural': 'Массив изображений №2 (уровень 2)',
            },
        ),
        migrations.CreateModel(
            name='Game_2_Obj_Level_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Название')),
                ('image_1', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №1')),
                ('image_2', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №2')),
                ('image_3', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №3')),
                ('image_4', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №4')),
                ('image_5', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение №5')),
            ],
            options={
                'verbose_name': 'Объект игры №2 (уровень 3)',
                'verbose_name_plural': 'Массив изображений №2 (уровень 3)',
            },
        ),
        migrations.AlterField(
            model_name='game_1_obj',
            name='last_changed',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последнее время изменений'),
        ),
    ]
