# Generated by Django 2.1.4 on 2018-12-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20181213_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_1_obj',
            options={'verbose_name': 'Объект игры № 1', 'verbose_name_plural': 'Массив изображений № 1'},
        ),
        migrations.AlterModelOptions(
            name='game_2_obj_level_1',
            options={'verbose_name': 'Объект игры № 4 (уровень 1)', 'verbose_name_plural': 'Группы изображений для уровня № 1'},
        ),
        migrations.AlterModelOptions(
            name='game_2_obj_level_2',
            options={'verbose_name': 'Объект игры № 4 (уровень 2)', 'verbose_name_plural': 'Группы изображений для уровня № 2'},
        ),
        migrations.AlterModelOptions(
            name='game_2_obj_level_3',
            options={'verbose_name': 'Объект игры № 4 (уровень 3)', 'verbose_name_plural': 'Группы изображений для уровня № 3'},
        ),
        migrations.AddField(
            model_name='game_2_obj_level_1',
            name='last_changed',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последнее время изменений'),
        ),
        migrations.AddField(
            model_name='game_2_obj_level_2',
            name='last_changed',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последнее время изменений'),
        ),
        migrations.AddField(
            model_name='game_2_obj_level_3',
            name='last_changed',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последнее время изменений'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_1',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_2',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_3',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
    ]
