# Generated by Django 2.1.4 on 2018-12-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20181214_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_3_Obj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='images/', verbose_name='Загрузить изображение')),
                ('verb', models.CharField(max_length=100, verbose_name='Глагол')),
                ('last_changed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последнее время изменений')),
            ],
            options={
                'verbose_name': 'Объект игры № 5 ',
                'verbose_name_plural': 'Массив изображений № 3',
            },
        ),
    ]
