# Generated by Django 2.1.4 on 2018-12-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_3_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.FilePathField(null=True, verbose_name='Фото'),
        ),
    ]
