# Generated by Django 2.1.4 on 2018-12-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20181222_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
