# Generated by Django 2.1.4 on 2019-01-09 19:40

from django.db import migrations, models
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20181222_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код из смс'),
        ),
        migrations.AlterField(
            model_name='game_1_obj',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
