# Generated by Django 2.1.4 on 2019-01-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20190109_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='description',
            field=models.CharField(default='change me', help_text='Впишите текст с нужным склонением выбранного цвета', max_length=100, verbose_name='Цвет со склонением'),
            preserve_default=False,
        ),
    ]
