# Generated by Django 2.1.4 on 2019-01-17 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_color_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='end_time',
        ),
        migrations.AddField(
            model_name='statistic',
            name='continuance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Продолжительность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='correct_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент верно выполненных'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='game',
            field=models.IntegerField(help_text='Целочисленное значение от 1 до 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Номер игры'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='level',
            field=models.IntegerField(help_text='Целочисленное значение от 1 до 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень игры'),
        ),
    ]
