# Generated by Django 2.1.4 on 2019-01-26 10:15

from django.db import migrations, models
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20190117_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_1_obj',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='game_1_obj',
            name='description_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Название на английском'),
        ),
        migrations.AddField(
            model_name='game_2_obj_level_1',
            name='description_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Название группы на английском'),
        ),
        migrations.AddField(
            model_name='game_2_obj_level_2',
            name='description_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Название группы на английском'),
        ),
        migrations.AddField(
            model_name='game_2_obj_level_3',
            name='description_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Название группы на английском'),
        ),
        migrations.AddField(
            model_name='game_3_obj',
            name='verb_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Глагол на английском'),
        ),
        migrations.AlterField(
            model_name='game_1_obj',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='game_1_obj',
            name='image',
            field=models.ImageField(help_text='до 5 мб', null=True, upload_to='images/', verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_1',
            name='image_1',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №1'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_1',
            name='image_2',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №2'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_2',
            name='image_1',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №1'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_2',
            name='image_2',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №2'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_2',
            name='image_3',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №3'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_3',
            name='image_1',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №1'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_3',
            name='image_2',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №2'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_3',
            name='image_3',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №3'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_3',
            name='image_4',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №4'),
        ),
        migrations.AlterField(
            model_name='game_2_obj_level_3',
            name='image_5',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение №5'),
        ),
        migrations.AlterField(
            model_name='game_3_obj',
            name='image_1',
            field=models.ImageField(help_text='до 5 мб', upload_to='images/', verbose_name='Загрузить изображение'),
        ),
    ]
