# Generated by Django 2.1.4 on 2019-01-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20190126_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Child', verbose_name='Ребенок'),
        ),
    ]
