# Generated by Django 2.1.5 on 2019-02-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20190209_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_1_obj',
            name='category_eng',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='color_eng',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='compound_question_eng',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='definition_question_eng',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='form_eng',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='functional_question_eng',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='material_eng',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='quantity_eng',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='sub_category_eng',
        ),
        migrations.AddField(
            model_name='category',
            name='category_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Категория на английском'),
        ),
        migrations.AddField(
            model_name='color',
            name='color_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Цвет на английском'),
        ),
        migrations.AddField(
            model_name='compoundquestion',
            name='part_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Составная часть вопроса на английском'),
        ),
        migrations.AddField(
            model_name='definitionquestion',
            name='definition_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Определение в виде вопроса на английском'),
        ),
        migrations.AddField(
            model_name='form',
            name='form_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Форма на английском'),
        ),
        migrations.AddField(
            model_name='functionalquestion',
            name='question_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Функциональный вопрос на английском'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Материал на английском'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='description_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Количество на английском'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_eng',
            field=models.CharField(default='change me', max_length=100, verbose_name='Подкатегория на английском'),
        ),
    ]
