# Generated by Django 2.1.5 on 2019-02-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20190209_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
