# Generated by Django 2.1.5 on 2019-02-12 11:05

from django.db import migrations, models
import games.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='category',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='color',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='color',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='compoundquestion',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='compoundquestion',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='definitionquestion',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='definitionquestion',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='form',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='form',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='functionalquestion',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='functionalquestion',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='material',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='material',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='audio',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='audio_eng',
            field=models.FileField(blank=True, help_text='до 5 мб', null=True, upload_to='audios/', validators=[games.validators.validate_file_extension, games.validators.validate_file_size], verbose_name='Аудио на английском'),
        ),
    ]
