# Generated by Django 2.1.5 on 2019-02-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20190212_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_1_obj',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='audio_eng',
        ),
    ]
