# Generated by Django 2.1.5 on 2019-02-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_quantitynew_subcategorynew'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_1_obj',
            name='quantity_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.QuantityNew', verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='game_1_obj',
            name='sub_category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.SubCategoryNew', verbose_name='Подкатегория'),
        ),
    ]
