# Generated by Django 2.1.5 on 2019-02-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_qs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_1_obj',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='game_1_obj',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
