# Generated by Django 2.1.5 on 2019-02-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20190226_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorynew',
            options={},
        ),
        migrations.RenameField(
            model_name='game_1_obj',
            old_name='quantity_new',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='game_1_obj',
            old_name='sub_category_new',
            new_name='sub_category',
        ),
    ]
