CATEGORIES = {
    'FRUITS': u'Фрукты',
    'VEGETABLES' : u'Овощи',
    'MUSICAL_INSTRUMENTS': u'Музыкальный инструменты',
    'DISHES': u'Посуда',
    'PETS': u'Домашние животные',
    'ANIMALS': u'Дикие животные',
    'INSECTS': u'Насекомые',
    'FOOTWEAR': u'Обувь',
    'SPORTS_EQUIPMENT': u'Спортивный инвентарь',
    'FOOD': u'Еда',
    'INSTRUMENTS': u'Инструменты',
    'STATIONERY': u'Канцелярские принадлежности',
    'BATH': u'Банные принадлежности',
    'PLANTS': u'Растения',
    'THINGS': u'Вещи',
    'FURNITURE': u'Мебель',
    'TOYS': u'Игрушки',
    'EQUIPMENT': u'Техника',
    'TRANSPORT': u'Транспорт',
}

FRUITS = {
    'Apple': u'Яблоко',
    'Grape': u'Виноград',
    'Granat': u'Гранат',
    'Cherry': u'Вишня',
    'Mandarin': u'Мандарин',
    'Strawberry': u'Клубника',
    'Pear': u'Груша',
    'Lemon': u'Лимон',
    'Pineapple': u'Ананас',
    'Peach': u'Персик',
    'Persimmon': u'Хурма',
    'Orage': u'Апельсин',
    'Banana': u'Банан',
    'Qiwi': u'Киви',
    'Melon': u'Дыня',
    'Watermelon': u'Арбуз',
    'Apricot': u'Абрикос',
    'Raspberry': u'Малина',
    'Blackberry': u'Ежевика',
    'Figs': u'Инжир',
    'Plum': u'Слива',
}

VEGETABLES = {
    'Broccoli': u'Брокколи',
    'Redis': u'Редиска',
    'Cabbage': u'Капуста',
    'Cucmber': u'Огурец',
    'Pumpkin': u'Тыква',
    'Carrot': u'Морковь',
    'Squash': u'Кабачок',
    'Pepper': u'Перец',
    'Eggplant': u'Баклажан',
    'Corn': u'Кукуруза',
    'Onion': u'Лук',
    'Garlic': u'Чеснок',
    'Potato': u'Картофель',
    'Beet': u'Свекла',
    'Tomato': u'Помидор',
    'Peas': u'Горох',
}

MUSICAL_INSTRUMENTS = {
    'Maracas': u'Маракасы',
    'Piano': u'Рояль',
    'Balalaika': u'Балалайка',
    'Fortepiano': u'Фортепиано',
    'Tambourine': u'Бубен',
    'Violin': u'Скрипка',
    'Drum': u'Барабан',
    'Guitar': u'Гитара',
    'Harmonic': u'Гармонь',
    'Block_flute': u'Блок-флейта',
    'Trumpet': u'Труба',
    'Glockenspiel': u'Металлофон',
    'Mouth_organ': u'Губная гармошка',
    'Bagpipes': u'Волынка',
    'Harp': u'Арфа',
}

DISHES = {
    'Knife': u'Нож',
    'Pan': u'Кастрюля',
    'Bowl': u'Миска',
    'Glass': u'Стакан',
    'Cup': u'Кружка',
    'Cup_rus': u'Чашка',
    'Spoon': u'Ложка',
    'Ladle': u'Половник',
    'Fork': u'Вилка',
    'Saucer': u'Блюдце',
    'Plate': u'Тарелка',
    'Cutting_board': u'Разделочная доска',
    'Jag': u'Кувшин',
    'Fripan': u'Сковорода',
    'Thermos': u'Термос',
    'Bucket': u'Ведро',
    'Grater': u'Терка',
    'Cupcake_mold': u'Форма для кексов',
}

PETS = {
    'Cat': u'Кошка',
    'Dog': u'Собака',
    'Lamb': u'Овечка',
    'Horse': u'Лошадь',
    'Cow': u'Корова',
    'Mouse': u'Мышь',
    'Bull': u'Бык',
    'Goat': u'Коза',
    'Pig': u'Свинья',
    'Camel': u'Верблюд',
    'Rabbit': u'Кролик',
}

WILDS = {
    'Elephant': u'Слон',
    'Giraffe': u'Жираф',
    'Tiger': u'Тигр',
    'Panther': u'Пантера',
    'Hedgehog': u'Ежик',
    'Kangaroo': u'Кенгуру',
    'Monkey': u'Обезьяна',
    'Gorilla': u'Горилла',
    'Panda': u'Панда',
    'Polar_bear': u'Белый медведь',
    'Brown_bear': u'Бурый медведь',
    'Squirrel': u'Белка',
    'Lion': u'Лев',
    'Hare': u'Заяц',
    'Frog': u'Лягушка',
    'Rhinoceros': u'Носорог',
    'Hippopotamus': u'Бегемот',
    'Zebra': u'Зебра',
    'Antelope': u'Антилопа',
    'Ferret': u'Хорек',
    'Leopard': u'Леопард',
    'Snake': u'Змея',
    'Lizard': u'Ящерица',
    'Crocodile': u'Крокодил',
    'Turtle': u'Черепаха',
}

BIRDS = {
    'Pelican': u'Пеликан',
    'Stork': u'Аист',
    'Ara_parrot': u'Попугай ара',
    'Ostrich': u'Страус',
    'Duck': u'Утка',
    'Crow': u'Ворона',
    'Dove': u'Голубь',
    'Sparrow': u'Воробей',
    'Eagle': u'Орел',
    'Hen': u'Курица',
    'Cock': u'Петух',
    'Goose': u'Гусь',
    'Turkey': u'Индюк',
    'Swallow': u'Ласточка',
    'Owl': u'Сова',
    'Peacock': u'Павлин',
    'Buzzard': u'Стервятник',
    'Tit': u'Синица',
    'Bullfinch': u'Снегирь',
    'Gull': u'Чайка',
    'Swan': u'Лебедь',
    'Flamingo': u'Фламинго',
    'Puffin': u'Тупик',
    'Penguin': u'Пингвин',
}

INSECTS = {
    'Early_butterfly': u'Мотылек',
    'Butterfly': u'Бабочка',
    'Horned_beetle': u'Рогатый жук',
    'ladybug': u'Божья коровка',
    'Grasshopper': u'Кузнечик',
    'Ant': u'Муравей',
    'Bee': u'Пчела',
    'Fly': u'Муха',
    'Mantis': u'Богомол',
    'Cockroach': u'Таракан',
    'Caterpillar': u'Гусеница',
    'Dragonfly': u'Стрекоза',
    'Mosquitto': u'Комар',
    'Firefighter_beetle': u'Жук пожарник',
    'Spider': u'Паук',
    'Scorpio': u'Скорпион',
}

CLOTHES = {
    'Cap': 'Шапка',
    'Hat': 'Шляпа',
    'Peaked_cap': 'Кепка',
    'Blazer': 'Пиджак',
    'Tights': 'Колготки',
    'Gloves': 'Перчатки',
    'Jacket': 'Куртка',
    'Socks': 'Носки',
    'Scarf': 'Шарф',
    'Mittens': 'Варежки',
    'Boxer_briefs': 'Трусы-боксеры',
    'Girls_baby_pants': 'Трусы детские девичьи',
    'Belt': 'Ремень',
    'Overalls': 'Комбинезон детский',
    'T-shirt': 'Футболка',
    'Short': 'Шорты',
    'Trouser': 'Брюки',
    'Sweatpants': 'Спортивные штаны',
    'Hoodie': 'Кофта с капюшоном',
    'Sweater': 'Свитер',
    'Jeans': 'Джинсы',
    'The_dress': 'Платье',
    'Skirt': 'Юбка',
    'Tie': 'Галстук',
    'Shirt': 'Рубашка',
    'Wristwatch': 'Часы наручные',
}

FOOTWEAR = {
    'High_heel_shoes': 'Туфли на каблуке',
    'Shoes_for_men': 'Ботинки мужские',
    'Kids_boots': 'Сапоги детские',
    'Rubber_boots': 'Сапоги резиновые',
    'Sneakers': 'Кроссовки',
    'Slippers_home': 'Тапочки домашние',
    'Flip_flops': 'Шлепанцы',
    'Sandals': 'Сандали',
    'Pointe_shoes': 'Пуанты',
    'Boots': 'бутсы',
}

SPORTS_EQUIPMENT = {
    'Soccer_ball': 'Футбольный мяч',
    'Basketball': 'Баскетбольный мяч',
    'Tennis_ball': 'Теннисный мяч',
    'Racket_for_tennis_big': 'Ракетка для тенниса большого',
    'Racket_for_tennis_small': 'Ракетка для тенниса маленького',
    'Badminton_racket': 'Ракетка для бадминтона',
    'Dumbbells': 'Гантели',
    'Jump_rope': 'Скакалка',
    'Barbell': 'Штанга',
    'Boxing_pear': 'Груша боксерская',
    'Boxing_gloves': 'Боксерские перчатки',
    'Skiing': 'Лыжи',
    'Skates': 'Коньки',
    'Skittles': 'Кегли',
    'Flippers': 'Ласты',
    'Hockey_stick': 'Хоккейная клюшка',
    'Snowboard': 'Сноуборд',
    'Ski_mask': 'Лыжная маска',
    'Cycling_helmet': 'Шлем велосипедный',
    'Gymnastic_hoop': 'Обруч гимнастический',
    'Horizontal_bar': 'Турник',
    'Swedish_wall': 'Шведская стенка',
    'Exercise_bike': 'Велотренажер',
    'Treadmill': 'Беговая дорожка',
    'Skateboard': 'Скейтборд',
    'Sled': 'Санки',
    'Chess': 'Шахматы',
    'Fencing_rapiers': 'Фехтовальные рапиры',
    'Bow': 'Лук для стрельбы',
}

FOOD = {
    'Pasta': 'Макароны',
    'Cutlet': 'Котлета',
    'Biscuit': 'Печенье',
    'Pretzel': 'Крендель',
    'Bread': 'Хлеб',
    'Wafer': 'Вафля',
    'Cup_cake': 'Кекс',
    'Candies': 'Конфеты',
    'Cake': 'Торт',
    'Butter': 'Масло',
    'Milk': 'Молоко',
    'Cheese': 'Сыр',
    'Pic': 'Рис',
    'Buckwheat': 'Гречка',
    'Eggs': 'Яйца',
    'Sausages': 'Сосиски',
    'Sausage': 'Колбаса',
    'Chocolate': 'Шоколад',
    'The_juice': 'Сок',
    'Ice_cream_cones': 'Мороженое в рожке',

}

INSTRUMENTS = {
    'Hammer': 'Молоток',
    'Screwdriver': 'Отвертка',
    'Nail': 'Гвоздь',
    'Nut': 'Гайка',
    'Bolt': 'Болт',
    'Drill': 'Дрель',
    'Adjustable_wrench': 'Разводной ключ',

}

STATIONERY = {
    'Pencil': 'Карандаш',
    'Pen': 'Ручка',
    'Marker pen': 'Фломастер',
    'Paints': 'Краски',
    'Brush': 'Кисточка',
    'Scissors': 'Ножницы',
    'Album': 'Альбом',
    'Notebook': 'Тетрадь',
    'Portfolio': 'Портфель',
}

BATH_ACCESSORIES = {
    'Bathrobe': 'Халат',
    'Towel': 'Полотенце',
    'Hairbrush': 'Расческа',
    'Toothbrush': 'Зубная щетка',
    'Toothpaste': 'Зубная паста',
    'Soap': 'Мыло',
    'Bast': 'Мочалка',
    'Sponge': 'Губка',
    'Pin': 'Прищепка',
    'Slippers': 'Тапочки',
}

PLANTS = {
    'Tree': 'Дерево',
    'Flower': 'Цветок',
    'Christmas_tree': 'Елка',
    'Grass': 'Трава',
    'Leaf': 'Листик',
    'Bush': 'Куст',
}

THINGS = {
    'Box': 'Коробка',
    'Padlock': 'Замок навесной',
    'Suitcase': 'Чемодан',
    'Umbrella': 'Зонтик',
}


FURNITURE = {
    'cupboard': 'шкаф',
    'chair': 'стул',
    'bed': 'кровать',
    'table': 'стол',
    'stool': 'табуретка',
    'sofa': 'диван',
    'armchair': 'кресло',
    'chest_of_drawers': 'комод',
    'floor_lamp': 'торшер',
    'sock_lamp': 'лампа настолькная',
}

TOYS = {
    'Teddy_bear': 'Плюшевый медведь',
    'Dish_on_the_children_table': 'Посудка на детском столике',
    'Wooden_typewriter': 'Деревянная машинка',
    'Drum': 'Барабан игрушка',
    'Many_colored_pencils': 'Много цветных карандашей',
    'Cube': 'Кубик',
    'Truck': 'Грузовик игрушка',
    'Ball': 'Мяч',
    'Aircraft': 'Игрушка самолет',
    'Pyramid': 'Пирамидка',
    'Lego': 'Конструктор лего',
    'Beanbag': 'Погремушка',
    'Bicycle': 'Велосипед игрушка',
    'Rocking_horse': 'Лошадка-качалка',
    'Book': 'Книга',
    'Balloon': 'Воздушный шарик',
    'Swing': 'Качели',
}

EQUIPMENT = {
    'Electric_kettle': 'Электрический чайник',
    'Iron': 'Утюг',
    'Fridge': 'Холодильник',
    'A_vacuum_cleaner': 'Пылесос',
    'Microwave': 'Микроволновая печь',
    'Washing_machine': 'Стиральная машинка',
    'Plate': 'Плита',
    'Computer': 'Компьютер',
    'Heater_radiator': 'Обогреватель – радиатор',
    'Headbands_headband': 'Наушники ободочные на голову',
    'Remote_controller': 'Пульт',
    'Television': 'Телевизор',
    'Camera': 'Фотоаппарат',
    'Phone': 'Телефон',
    'Hair_dryer': 'Фен',
    'Clock': 'Часы',
}

TRANSPORT = {
    'Truck_wagon': 'Грузовик – фура',
    'A_train': 'Поезд',
    'Motorcycle': 'Мотоцикл',
    'Helicopter': 'Вертолет',
    'Tractor': 'Трактор',
    'Excavator': 'Экскаватор',
    'Aircraft': 'Самолет',
    'Car': 'Автомобиль',
    'Bus': 'Автобус',
    'Two-tier_bus': 'Автобус двухярусный',
    'Truck': 'Грузовик',
    'Bicycle': 'Велосипед',
    'Steamer': 'Пароход',
}

COLOR = {
    'not specified': 'не указано',
    'Yellow': 'Желтый',
    'Red': 'Красный',
    'Green': 'Зеленый',
    'Blue': 'Синий',
    'White': 'Белый',
    'Black': 'Черный',
    'Orange': 'Оранжевый',
    'Lightblue': 'Голубой',
    'Purple': 'Фиолетовый',
    'Brown': 'Коричневый',
    'Gray': 'Серый',
    'Pink': 'Розовый',
}

MATERIAL = {
    'not_specified': 'не указано',
    'glass': 'стеклянный',
    # 'Wooden': 'Деревянная',
    'Wooden': 'Деревянный',
    'Iron': 'Железный',
    # 'Iron': 'Железное',
    # 'Iron': 'Железная',

}

FORM = {
    'not_specified': 'не указано',
    'round': 'круглый',
    # 'round': 'круглое',
    # 'round': 'круглая',
    'square': 'квадратный',
    # 'square': 'квадратная',
    # 'square': 'квадратное',

}

FUNCTIONAL_QUESTIONS = {
    'not_specified': 'не указано',
    'What_to_eat': 'Что едят',
    'What_is_the_music': 'На чем играют музыку',
    'What_is_water_poured_from': 'Из чего наливают воду',
    'Where_clothes_are_stored': 'Где хранят одежду',
    'On_what_sit': 'На чем сидят',
    'What_sleep': 'На чем спят',
    'What_shines': 'Что светит',
    'What_is_playing': 'С чем играют',
    'What_can_be_rolled': 'Что можно катать',
    'Why_knock_on': 'По чему стучат',
    'What_draw': 'Чем рисуют',
    'What_they_build': 'Из чего строят',
    'What_throw': 'Что бросают',
    'What_is_collected': 'Что собирают',
    'On_what_ride': 'На чем катаются',
    'What_is_read': 'Что читают',
    'What_is_inflated': 'Что надувают',
    'On_what_swing': 'На чем качаются',
    'What_warms_the_water': 'Что греет воду',
    'What_stroking': 'Чем гладят',
    'Where_are_the_products_stored': 'Где хранят продукты',
    'that_removes_dust': 'что убирает пыль',
    'what_makes_food_warm': 'в чем греют еду',
    'what_erases': 'что стирает',
    'on_what_they_cook': 'на чем готовят',
    'what_is_calling': 'что звонит',
    'than_dry_hair': 'чем сушат волосы',
    'what_time_shows': 'что показывает время',
    'what_goes': 'что едет',
    'what_flies': 'что летает',
    'what_is_digging': 'что копает',
    'what_floats_on_water': 'что плавает по воде',
    'what_can_be_cut': 'чем можно резать',
    'what_can_you_cook': 'в чем можно варить',
    'from_which_they_drink': 'из чего пьют',
    'what_to_eat': 'чем едят',
    'where_to_drink': 'из чего можно пить',
    'what_is_fried': 'на чем жарят',
    'what_can_be_baked': 'в чем можно печь',
    'who_meows': 'кто мяукает',
    'who_barks': 'кто гавкает',
    'who_grunts': 'кто хрюкает',
    'who_roars': 'кто рычит',
    'who_is_jumping': 'кто прыгает',
    'who_gnaws_nuts': 'кто грызет орехи',
    'who_flies': 'кто летает',
    'who_quacks': 'кто крякает',
    'who_bears_eggs': 'кто несет яйца',
    'who_crows': 'кто кукарекает',
    'who_croaks': 'кто каркает',
    'who_buzzes': 'кто жужжит',
    'what_is_worn_on_the_head': 'что носят на голове',
    'what_to_wear': 'что можно надеть',
    'what_is_worn_on_hand_to_wear': 'что носят на руке надеть',
    'what_they_wear_on_their_feet': 'что надевают на ноги',
    'what_do_ballerinas_wear': 'что носят балерины',
    'what_to_wear_on_the_beach': 'что надевают на пляже',
    'what_football_players_wear': 'что носят футболисты',
    'than_beat_the_ball': 'чем отбивают мяч',
    'why_do_boxers_beat': 'по чему бьют боксеры',
    'what_are_boxers_wearing': 'что носят боксеры',
    'on_what_ride_on_ice': 'на чем катаются по льду',
    'than_playing_hockey': 'чем играют в хоккей',
    'on_what_ride_in_the_snow': 'на чем катаются по снегу',
    'what_are_they_catching_up': 'на чем подтягиваются',
    'on_what_ride_from_a_hill': 'на чем катаются с горки',
    'that_shoots_arrows': 'что стреляет стрелами',
    'what_is_pedaling': 'на чем крутят педали',
    'than_hammer_nails': 'чем забивают гвозди',
    'than_tighten_the_screws': 'чем закручивают винтики',
    'what_are_the_walls_drilled': 'чем сверлят стены',
    'what_they_write': 'чем пишут',
    'what_draw': 'в чем рисуют',
    'what_are_the_textbooks': 'в чем носят учебники',
    'what_to_wear_after_swimming': 'что надевают после купания',
    'than_brushing_your_teeth': 'чем чистят зубы',
    'than_comb': 'чем расчесываются',
    'what_wash_hands': 'чем моют руки',
    'what_protects_from_rain': 'что защищает от дождя',
    'Who_croaks': 'Кто квакает',

}

COMPOUND_QUESTIONS = {
    'not_specified': 'не указано',
    'what_has_wheels': 'у чего есть колеса',
    'what_have_pages': 'у чего есть страницы',
    'what_have_buttons': 'у чего есть кнопки',
    'what_has_a_steering_wheel': 'у чего есть руль',
    'what_has_wings': 'у чего есть крылья',
    'what_have_keys': 'у чего есть клавиши',
    'who_has_horns': 'у кого есть рога',
    'who_has_a_penny': 'у кого есть пятачок',
    'who_has_a_hump': 'у кого есть горб',
    'who_has_a_trunk': 'у кого есть хобот',
    'who_has_a_long_neck': 'у кого длинная шея',
    'who_has_needles': 'у кого есть иголки',
    'who_has_yellow_breast': 'у кого желтая грудка',
    'who_has_red_breast': 'у кого красная грудка',
    'what_have_stud': 'у чего есть пуговицы',
    'what_have_strings': 'у чего есть струны',
    'Who_has_strips': 'У кого есть полоски',
    'what_has_a_hood': 'у чего есть капюшон',

}

DEFINITION_QUESTION = {
    'not_specified': 'не указано',
    'it_is_made_by_man': 'это сделано человеком',
    'it_is_alive': 'это живое',
    'it_is_edible': 'это съедобно',
}

QUANTITY = {
    'single': 'один',
    'several': 'несколько ',
    'not_spicified': 'не указано',
}
